In [42]:
# import libraries

import pandas as pd

In [ ]:
a_data = pd.read_json("./data/input_a.json")

In [44]:
a_data.head()

          id       merchant  amount                         ts
0  a_h246316    Netflix.com  372.07  2026-01-12 12:13:44 +0530
1  a_b131244    NETFLIX,COM   48.03  2026-01-12 13:50:25 +0530
2  a_r308496  AMZN MKTPLACE  255.15  2026-01-12 10:14:29 +0530
3  a_s391704    NETFLIX,COM  212.66  2026-01-12 14:05:19 +0530
4  a_w543143  Local Grocery  380.61  2026-01-12 11:27:11 +0530

In [ ]:
b_data = pd.read_json("./data/input_b.json")

In [46]:
b_data.head()

          id         merchant  amount                         ts
0  b_m407979     netflix com   372.30  2026-01-12 12:13:38 +0530
1  b_q609288      NETFLIX,COM   47.83  2026-01-12 13:51:35 +0530
2  b_s591877    amzn mktplace  255.36  2026-01-12 10:14:48 +0530
3  b_k749667      NETFLIX,COM  212.45  2026-01-12 14:04:15 +0530
4  b_z126047  LOCAL  GROCERY   380.86  2026-01-12 11:27:07 +0530

In [ ]:
import json

with open('./data/merchant_map.json', 'r') as file:
    matching_rules = json.load(file)

In [48]:
matching_rules

{'AMZN MKTPLACE': 'Amazon',
 'Amazon Marketplace': 'Amazon',
 'AMAZON MARKETPLACE': 'Amazon',
 'STARBUCKS 123': 'Starbucks',
 'Starbucks Store 123': 'Starbucks',
 'UBER BV': 'Uber',
 'Uber Trip': 'Uber',
 'NETFLIX': 'Netflix',
 'Netflix.com': 'Netflix',
 'LOCAL GROCERY': 'Local Grocery',
 'Local Grocery': 'Local Grocery'}

In [49]:
list(a_data["merchant"].unique())

['Netflix.com',
 'NETFLIX,COM',
 'AMZN MKTPLACE',
 'Local Grocery',
 'STARBUCKS 123',
 'Amazon Marketplace',
 'LOCAL  GROCERY ',
 'STARBUCKS.123',
 'Starbucks Store, 123',
 'Coffee Shop 77',
 ' starbucks 123 ',
 'AMZN. MKTPLACE',
 'Local-Grocery',
 'Uber  Trip',
 'LOCAL GROCERY',
 'uber trip',
 'NETFLIX.COM',
 'amzn mktplace',
 'UBER BV',
 'Pharmacy 22',
 'Amazon   Marketplace',
 'UBER, BV',
 'NETFLIX',
 'AMAZON MARKETPLACE',
 'local grocery',
 'Starbucks Store 123',
 'Uber Trip',
 'Fuel Station 9',
 ' netflix com ',
 'Restaurant ABC',
 'Ecomm Seller X']

In [50]:
list(b_data["merchant"].unique())

[' netflix com ',
 'NETFLIX,COM',
 'amzn mktplace',
 'LOCAL  GROCERY ',
 'STARBUCKS 123',
 'AMZN MKTPLACE',
 'LOCAL  GROCERY',
 'STARBUCKS.123',
 'LOCAL GROCERY',
 'Starbucks Store, 123',
 'Coffee Shop 77',
 'AMZN. MKTPLACE',
 'Local-Grocery',
 'Uber  Trip',
 'Amazon   Marketplace',
 'uber trip',
 'NETFLIX.COM',
 'Amazon Marketplace',
 'UBER BV',
 'UBER, BV',
 'NETFLIX',
 'starbucks 123',
 'AMAZON MARKETPLACE',
 ' starbucks 123 ',
 'local grocery',
 'Local Grocery',
 'Fuel Station 9',
 'Starbucks Store 123',
 'netflix com',
 'Restaurant ABC',
 'Uber Trip',
 'Pharmacy 22',
 'Ecomm Seller X',
 'Netflix.com']

In [51]:
a_data['merchant'] = a_data['merchant'].str.replace(',','')
a_data['merchant'] = a_data['merchant'].str.replace('-','')
a_data['merchant'] = a_data['merchant'].str.replace(' ','')
a_data['merchant'] = a_data['merchant'].str.replace('.','')

In [52]:
list(a_data["merchant"].unique())

['Netflixcom',
 'NETFLIXCOM',
 'AMZNMKTPLACE',
 'LocalGrocery',
 'STARBUCKS123',
 'AmazonMarketplace',
 'LOCALGROCERY',
 'StarbucksStore123',
 'CoffeeShop77',
 'starbucks123',
 'UberTrip',
 'ubertrip',
 'amznmktplace',
 'UBERBV',
 'Pharmacy22',
 'NETFLIX',
 'AMAZONMARKETPLACE',
 'localgrocery',
 'FuelStation9',
 'netflixcom',
 'RestaurantABC',
 'EcommSellerX']

In [53]:
b_data['merchant'] = b_data['merchant'].str.replace(',','')
b_data['merchant'] = b_data['merchant'].str.replace('-','')
b_data['merchant'] = b_data['merchant'].str.replace(' ','')
b_data['merchant'] = b_data['merchant'].str.replace('.','')

In [54]:
list(b_data["merchant"].unique())

['netflixcom',
 'NETFLIXCOM',
 'amznmktplace',
 'LOCALGROCERY',
 'STARBUCKS123',
 'AMZNMKTPLACE',
 'StarbucksStore123',
 'CoffeeShop77',
 'LocalGrocery',
 'UberTrip',
 'AmazonMarketplace',
 'ubertrip',
 'UBERBV',
 'NETFLIX',
 'starbucks123',
 'AMAZONMARKETPLACE',
 'localgrocery',
 'FuelStation9',
 'RestaurantABC',
 'Pharmacy22',
 'EcommSellerX',
 'Netflixcom']

In [55]:
matching_rules_dictionary = {"Name":matching_rules.keys(), "Normal_Name" : matching_rules.values()}

matching_rules_df = pd.DataFrame.from_dict(matching_rules_dictionary)

In [56]:
matching_rules_df

                   Name    Normal_Name
0         AMZN MKTPLACE         Amazon
1    Amazon Marketplace         Amazon
2    AMAZON MARKETPLACE         Amazon
3         STARBUCKS 123      Starbucks
4   Starbucks Store 123      Starbucks
5               UBER BV           Uber
6             Uber Trip           Uber
7               NETFLIX        Netflix
8           Netflix.com        Netflix
9         LOCAL GROCERY  Local Grocery
10        Local Grocery  Local Grocery

In [57]:
matching_rules_df['Name'] = matching_rules_df['Name'].str.replace(',','')
matching_rules_df['Name'] = matching_rules_df['Name'].str.replace('-','')
matching_rules_df['Name'] = matching_rules_df['Name'].str.replace('.','')
matching_rules_df['Name'] = matching_rules_df['Name'].str.replace(' ','')

In [58]:
matching_rules_df

                 Name    Normal_Name
0        AMZNMKTPLACE         Amazon
1   AmazonMarketplace         Amazon
2   AMAZONMARKETPLACE         Amazon
3        STARBUCKS123      Starbucks
4   StarbucksStore123      Starbucks
5              UBERBV           Uber
6            UberTrip           Uber
7             NETFLIX        Netflix
8          Netflixcom        Netflix
9        LOCALGROCERY  Local Grocery
10       LocalGrocery  Local Grocery

In [59]:
matching_rules_df_dict = matching_rules_df.to_dict()

In [60]:
matching_rules_df_dict_key = matching_rules_df["Name"]
matching_rules_df_dict_value = matching_rules_df["Normal_Name"]

In [61]:
matching_rules_normal_dict =  dict(zip(matching_rules_df_dict_key, matching_rules_df_dict_value))

In [62]:
matching_rules_normal_dict

{'AMZNMKTPLACE': 'Amazon',
 'AmazonMarketplace': 'Amazon',
 'AMAZONMARKETPLACE': 'Amazon',
 'STARBUCKS123': 'Starbucks',
 'StarbucksStore123': 'Starbucks',
 'UBERBV': 'Uber',
 'UberTrip': 'Uber',
 'NETFLIX': 'Netflix',
 'Netflixcom': 'Netflix',
 'LOCALGROCERY': 'Local Grocery',
 'LocalGrocery': 'Local Grocery'}

In [72]:
a_data["merchant"] = a_data["merchant"].map(matching_rules_normal_dict).fillna(a_data["merchant"])
b_data["merchant"] = b_data["merchant"].map(matching_rules_normal_dict).fillna(b_data["merchant"])

In [73]:
list(b_data["merchant"].unique())

['netflixcom',
 'NETFLIXCOM',
 'amznmktplace',
 'Local Grocery',
 'Starbucks',
 'Amazon',
 'CoffeeShop77',
 'Uber',
 'ubertrip',
 'Netflix',
 'starbucks123',
 'localgrocery',
 'FuelStation9',
 'RestaurantABC',
 'Pharmacy22',
 'EcommSellerX']

In [71]:
list(a_data["merchant"].unique())

['Netflix',
 'NETFLIXCOM',
 'Amazon',
 'Local Grocery',
 'Starbucks',
 'CoffeeShop77',
 'starbucks123',
 'Uber',
 'ubertrip',
 'amznmktplace',
 'Pharmacy22',
 'localgrocery',
 'FuelStation9',
 'netflixcom',
 'RestaurantABC',
 'EcommSellerX']

# Actual Soultion

In [74]:
import json
import re
import csv
import heapq
from datetime import datetime, timezone, timedelta
from collections import defaultdict
from dataclasses import dataclass, field
from typing import Optional

print("✅ Imports OK")

✅ Imports OK

In [75]:
@dataclass
class Transaction:
    id: str
    merchant_raw: str
    amount: float
    ts_raw: str
    ts: datetime          # timezone-aware UTC datetime
    merchant_norm: str = ""   # filled during preprocessing

    def __repr__(self):
        return (f"Txn({self.id}, merchant={self.merchant_norm!r}, "
                f"amount={self.amount}, ts={self.ts.isoformat()})")


@dataclass
class MatchedPair:
    txn_a: Transaction
    txn_b: Transaction
    time_diff_sec: float
    amount_diff: float


@dataclass
class UnmatchedTxn:
    txn: Transaction
    reason: str          # "no_merchant_match" | "no_amount_match" | "no_timestamp_match"


print("✅ Data classes defined")

✅ Data classes defined

In [76]:
def parse_ts(ts_str: str) -> datetime:
    """
    Parse timestamps like '2026-01-12 10:14:29 +0530'.
    Returns a UTC-normalised aware datetime so all comparisons are apples-to-apples.
    """
    # Python's %z handles '+0530' from Python 3.7+
    dt = datetime.strptime(ts_str.strip(), "%Y-%m-%d %H:%M:%S %z")
    return dt.astimezone(timezone.utc)


def _strip_normalize(text: str) -> str:
    """Lowercase, remove punctuation & extra spaces."""
    text = text.lower()
    text = re.sub(r"[^a-z0-9 ]", " ", text)   # replace punct with space
    text = re.sub(r"\s+", " ", text).strip()
    return text


def normalize_merchant(raw: str, merchant_map: dict[str, str]) -> str:
    """
    1. Direct map lookup (original casing).
    2. Case-insensitive map lookup.
    3. Strip & normalize, then try again.
    4. Fall back to the stripped form.

    The result is a canonical merchant key used for grouping.
    """
    # 1. direct
    if raw in merchant_map:
        return merchant_map[raw].lower()

    # 2. case-insensitive exact
    raw_stripped = raw.strip()
    for k, v in merchant_map.items():
        if k.strip().lower() == raw_stripped.lower():
            return v.lower()

    # 3. strip & normalize, then map
    norm = _strip_normalize(raw)
    for k, v in merchant_map.items():
        if _strip_normalize(k) == norm:
            return v.lower()

    # 4. fallback — return the stripped-normalized string itself
    return norm


def load_transactions(path: str, merchant_map: dict) -> list[Transaction]:
    with open(path, "r") as f:
        raw_list = json.load(f)

    txns = []
    for r in raw_list:
        ts = parse_ts(r["ts"])
        t = Transaction(
            id=r["id"],
            merchant_raw=r["merchant"],
            amount=float(r["amount"]),
            ts_raw=r["ts"],
            ts=ts,
        )
        t.merchant_norm = normalize_merchant(r["merchant"], merchant_map)
        txns.append(t)
    return txns


def amount_within_tolerance(a: float, b: float) -> bool:
    diff = abs(a - b)
    if diff <= 0.50:
        return True
    if max(a, b) > 0 and diff / max(a, b) <= 0.001:   # 0.1 %
        return True
    return False


def time_within_tolerance(ta: datetime, tb: datetime, max_sec: int = 120) -> bool:
    return abs((ta - tb).total_seconds()) <= max_sec


print("✅ Normalization utilities defined")

✅ Normalization utilities defined

In [77]:
def build_candidate_pairs(
    group_a: list[Transaction],
    group_b: list[Transaction],
) -> list[tuple[float, float, int, int]]:
    """
    For a single merchant group, find all (a, b) pairs that satisfy
    amount + timestamp tolerances.

    Returns list of (time_diff_sec, amount_diff, idx_a, idx_b) sorted by
    (time_diff_sec, amount_diff) — best match first.

    Uses a sorted-time two-pointer window to avoid O(n²) scanning.
    """
    # Sort both by timestamp
    a_sorted = sorted(enumerate(group_a), key=lambda x: x[1].ts)
    b_sorted = sorted(enumerate(group_b), key=lambda x: x[1].ts)

    candidates = []
    j_start = 0

    for ia, ta in a_sorted:
        # Advance j_start to the earliest b that might be within 2 min
        while j_start < len(b_sorted):
            _, tb_start = b_sorted[j_start]
            if (ta.ts - tb_start.ts).total_seconds() > 120:
                j_start += 1
            else:
                break

        # Scan forward from j_start while b is within window
        for jj in range(j_start, len(b_sorted)):
            jb, tb = b_sorted[jj]
            dt = (tb.ts - ta.ts).total_seconds()
            if dt > 120:   # b is already past the window
                break
            if abs(dt) <= 120 and amount_within_tolerance(ta.amount, tb.amount):
                candidates.append((
                    abs(dt),
                    abs(ta.amount - tb.amount),
                    ia,
                    jb,
                ))

    candidates.sort(key=lambda x: (x[0], x[1]))
    return candidates


def greedy_match(
    group_a: list[Transaction],
    group_b: list[Transaction],
) -> tuple[list[MatchedPair], list[Transaction], list[Transaction]]:
    """
    Given pre-filtered same-merchant lists, greedily pick best-scoring pairs
    (minimise time diff, then amount diff) ensuring each txn used at most once.
    """
    candidates = build_candidate_pairs(group_a, group_b)

    used_a: set[int] = set()
    used_b: set[int] = set()
    matched: list[MatchedPair] = []

    for time_diff, amt_diff, ia, ib in candidates:
        if ia in used_a or ib in used_b:
            continue
        used_a.add(ia)
        used_b.add(ib)
        matched.append(MatchedPair(
            txn_a=group_a[ia],
            txn_b=group_b[ib],
            time_diff_sec=time_diff,
            amount_diff=amt_diff,
        ))

    unmatched_a = [group_a[i] for i in range(len(group_a)) if i not in used_a]
    unmatched_b = [group_b[i] for i in range(len(group_b)) if i not in used_b]
    return matched, unmatched_a, unmatched_b


def classify_unmatched_reason(
    txn: Transaction,
    candidates_same_merchant: list[Transaction],
    is_from_a: bool,
) -> str:
    """
    Determine WHY a transaction couldn't be matched.
    We look at what was available on the other side (same merchant group).
    """
    if not candidates_same_merchant:
        return "no_merchant_match"

    # Check if any candidate had an acceptable amount
    amount_ok = any(amount_within_tolerance(txn.amount, c.amount)
                    for c in candidates_same_merchant)
    if not amount_ok:
        return "no_amount_match"

    # Amount was fine but time window never aligned
    return "no_timestamp_match"


print("✅ Matching engine defined")

✅ Matching engine defined

In [78]:
def reconcile(
    txns_a: list[Transaction],
    txns_b: list[Transaction],
) -> dict:
    """
    Main reconciliation pipeline.
    Returns a structured report dict.
    """
    # ── Group by normalised merchant ─────────────────────────────────────────
    groups_a: dict[str, list[Transaction]] = defaultdict(list)
    groups_b: dict[str, list[Transaction]] = defaultdict(list)

    for t in txns_a:
        groups_a[t.merchant_norm].append(t)
    for t in txns_b:
        groups_b[t.merchant_norm].append(t)

    all_merchants = set(groups_a.keys()) | set(groups_b.keys())

    matched_pairs: list[MatchedPair] = []
    unmatched_a: list[UnmatchedTxn] = []
    unmatched_b: list[UnmatchedTxn] = []

    for merchant in sorted(all_merchants):
        ga = groups_a.get(merchant, [])
        gb = groups_b.get(merchant, [])

        if not ga:
            # All B transactions have no merchant match on A side
            for t in gb:
                unmatched_b.append(UnmatchedTxn(t, "no_merchant_match"))
            continue

        if not gb:
            for t in ga:
                unmatched_a.append(UnmatchedTxn(t, "no_merchant_match"))
            continue

        pairs, rem_a, rem_b = greedy_match(ga, gb)
        matched_pairs.extend(pairs)

        # Classify remaining unmatched
        for t in rem_a:
            reason = classify_unmatched_reason(t, gb, is_from_a=True)
            unmatched_a.append(UnmatchedTxn(t, reason))

        for t in rem_b:
            reason = classify_unmatched_reason(t, ga, is_from_a=False)
            unmatched_b.append(UnmatchedTxn(t, reason))

    # ── Build report ─────────────────────────────────────────────────────────
    report = {
        "summary": {
            "total_a": len(txns_a),
            "total_b": len(txns_b),
            "matched_count": len(matched_pairs),
            "unmatched_a_count": len(unmatched_a),
            "unmatched_b_count": len(unmatched_b),
            "match_rate_a": f"{len(matched_pairs)/len(txns_a)*100:.1f}%",
            "match_rate_b": f"{len(matched_pairs)/len(txns_b)*100:.1f}%",
        },
        "matched_pairs": [
            {
                "txn_a": {
                    "id": p.txn_a.id,
                    "merchant_raw": p.txn_a.merchant_raw,
                    "merchant_norm": p.txn_a.merchant_norm,
                    "amount": p.txn_a.amount,
                    "timestamp": p.txn_a.ts_raw,
                },
                "txn_b": {
                    "id": p.txn_b.id,
                    "merchant_raw": p.txn_b.merchant_raw,
                    "merchant_norm": p.txn_b.merchant_norm,
                    "amount": p.txn_b.amount,
                    "timestamp": p.txn_b.ts_raw,
                },
                "time_diff_sec": round(p.time_diff_sec, 1),
                "amount_diff": round(p.amount_diff, 4),
            }
            for p in matched_pairs
        ],
        "unmatched_a": [
            {
                "id": u.txn.id,
                "merchant_raw": u.txn.merchant_raw,
                "merchant_norm": u.txn.merchant_norm,
                "amount": u.txn.amount,
                "timestamp": u.txn.ts_raw,
                "reason": u.reason,
            }
            for u in unmatched_a
        ],
        "unmatched_b": [
            {
                "id": u.txn.id,
                "merchant_raw": u.txn.merchant_raw,
                "merchant_norm": u.txn.merchant_norm,
                "amount": u.txn.amount,
                "timestamp": u.txn.ts_raw,
                "reason": u.reason,
            }
            for u in unmatched_b
        ],
    }
    return report, matched_pairs, unmatched_a, unmatched_b


print("✅ Reconciliation pipeline defined")

✅ Reconciliation pipeline defined

In [79]:
def write_json_report(report: dict, path: str = "reconciliation_report.json"):
    with open(path, "w") as f:
        json.dump(report, f, indent=2)
    print(f"📄 JSON report  → {path}")


def write_summary_txt(report: dict, path: str = "reconciliation_summary.txt"):
    s = report["summary"]
    lines = [
        "=" * 60,
        "  TRANSACTION RECONCILIATION — SUMMARY",
        "=" * 60,
        f"  System A transactions   : {s['total_a']:>6}",
        f"  System B transactions   : {s['total_b']:>6}",
        f"  Matched pairs           : {s['matched_count']:>6}  ({s['match_rate_a']} of A / {s['match_rate_b']} of B)",
        f"  Unmatched from A        : {s['unmatched_a_count']:>6}",
        f"  Unmatched from B        : {s['unmatched_b_count']:>6}",
        "=" * 60,
        "",
        "UNMATCHED A — by reason:",
    ]
    from collections import Counter
    a_reasons = Counter(u["reason"] for u in report["unmatched_a"])
    for reason, cnt in sorted(a_reasons.items()):
        lines.append(f"  {reason:<30}: {cnt}")
    lines += ["", "UNMATCHED B — by reason:"]
    b_reasons = Counter(u["reason"] for u in report["unmatched_b"])
    for reason, cnt in sorted(b_reasons.items()):
        lines.append(f"  {reason:<30}: {cnt}")
    lines += ["", "TOP 10 LARGEST AMOUNT DIFFERENCES (matched pairs):"]
    top10 = sorted(report["matched_pairs"], key=lambda x: x["amount_diff"], reverse=True)[:10]
    for p in top10:
        lines.append(
            f"  A:{p['txn_a']['id']:<18} B:{p['txn_b']['id']:<18}"
            f"  Δamt={p['amount_diff']:.4f}  Δtime={p['time_diff_sec']:.0f}s"
        )
    lines += ["", "TOP 10 LARGEST TIME DIFFERENCES (matched pairs):"]
    top10t = sorted(report["matched_pairs"], key=lambda x: x["time_diff_sec"], reverse=True)[:10]
    for p in top10t:
        lines.append(
            f"  A:{p['txn_a']['id']:<18} B:{p['txn_b']['id']:<18}"
            f"  Δtime={p['time_diff_sec']:.0f}s  Δamt={p['amount_diff']:.4f}"
        )

    text = "\n".join(lines)
    with open(path, "w") as f:
        f.write(text)
    print(f"📋 Summary text → {path}")
    print()
    print(text)


def write_csv_matched(matched_pairs: list[MatchedPair], path: str = "matched_pairs.csv"):
    with open(path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow([
            "a_id", "a_merchant_raw", "a_merchant_norm", "a_amount", "a_timestamp",
            "b_id", "b_merchant_raw", "b_merchant_norm", "b_amount", "b_timestamp",
            "time_diff_sec", "amount_diff",
        ])
        for p in matched_pairs:
            writer.writerow([
                p.txn_a.id, p.txn_a.merchant_raw, p.txn_a.merchant_norm,
                p.txn_a.amount, p.txn_a.ts_raw,
                p.txn_b.id, p.txn_b.merchant_raw, p.txn_b.merchant_norm,
                p.txn_b.amount, p.txn_b.ts_raw,
                round(p.time_diff_sec, 1), round(p.amount_diff, 4),
            ])
    print(f"📊 Matched CSV  → {path}")


def write_csv_unmatched(unmatched: list[UnmatchedTxn], path: str):
    with open(path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["id", "merchant_raw", "merchant_norm", "amount", "timestamp", "reason"])
        for u in unmatched:
            writer.writerow([
                u.txn.id, u.txn.merchant_raw, u.txn.merchant_norm,
                u.txn.amount, u.txn.ts_raw, u.reason,
            ])
    print(f"📊 Unmatched    → {path}")


print("✅ Output writers defined")

✅ Output writers defined

In [ ]:
def main(
    path_a: str = "./data/input_a.json",
    path_b: str = "./data/input_b.json",
    path_map: str = "./data/merchant_map.json",
):
    print("\n🔄 Loading data...")
    with open(path_map) as f:
        merchant_map = json.load(f)

    txns_a = load_transactions(path_a, merchant_map)
    txns_b = load_transactions(path_b, merchant_map)
    print(f"   Loaded {len(txns_a)} transactions from A, {len(txns_b)} from B")

    print("\n🔄 Running reconciliation...")
    report, matched_pairs, unmatched_a, unmatched_b = reconcile(txns_a, txns_b)

    print("\n🔄 Writing outputs...")
    write_json_report(report)
    write_summary_txt(report)
    write_csv_matched(matched_pairs)
    write_csv_unmatched(unmatched_a, "unmatched_a.csv")
    write_csv_unmatched(unmatched_b, "unmatched_b.csv")

    print("\n✅ Done! Files written:")
    print("   • reconciliation_report.json")
    print("   • reconciliation_summary.txt")
    print("   • matched_pairs.csv")
    print("   • unmatched_a.csv")
    print("   • unmatched_b.csv")

    return report


if __name__ == "__main__":
    report = main()

🔄 Loading data...
   Loaded 510 transactions from A, 500 from B

🔄 Running reconciliation...

🔄 Writing outputs...
📄 JSON report  → reconciliation_report.json
📋 Summary text → reconciliation_summary.txt

============================================================
  TRANSACTION RECONCILIATION — SUMMARY
============================================================
  System A transactions   :    510
  System B transactions   :    500
  Matched pairs           :    440  (86.3% of A / 88.0% of B)
  Unmatched from A        :     70
  Unmatched from B        :     60
============================================================

UNMATCHED A — by reason:
  no_amount_match               : 56
  no_timestamp_match            : 14

UNMATCHED B — by reason:
  no_amount_match               : 27
  no_timestamp_match            : 33

TOP 10 LARGEST AMOUNT DIFFERENCES (matched pairs):
  A:a_j616554          B:b_v950501           Δamt=0.3000  Δtime=85s
  A:a_u450905          B:b_u311245           Δamt=0.3000  Δtime=88s
  A:a_v571778          B:b_d550348           Δamt=0.3000  Δtime=78s
  A:a_c824586          B:b_near_q973061      Δamt=0.3000  Δtime=8s
  A:a_q409222          B:b_q160843           Δamt=0.3000  Δtime=54s
  A:a_r630041          B:b_t391511           Δamt=0.2900  Δtime=11s
  A:a_z141832          B:b_h765578           Δamt=0.2900  Δtime=68s
  A:a_a217301          B:b_s593056           Δamt=0.2900  Δtime=63s
  A:a_p120324          B:b_d694832           Δamt=0.2900  Δtime=56s
  A:a_y530728          B:b_y867747           Δamt=0.2900  Δtime=6s

TOP 10 LARGEST TIME DIFFERENCES (matched pairs):
  A:a_n627290          B:b_g682091           Δtime=90s  Δamt=0.1900
  A:a_u540781          B:b_t715277           Δtime=90s  Δamt=0.1800
  A:a_t770030          B:b_y645918           Δtime=90s  Δamt=0.2900
  A:a_v691912          B:b_n254910           Δtime=90s  Δamt=0.0900
  A:a_w399607          B:b_m573038           Δtime=90s  Δamt=0.1100
  A:a_q799539          B:b_j649374           Δtime=89s  Δamt=0.2400
  A:a_e418897          B:b_f267747           Δtime=89s  Δamt=0.1000
  A:a_l192410          B:b_c821807           Δtime=88s  Δamt=0.0900
  A:a_f310548          B:b_p650209           Δtime=88s  Δamt=0.2600
  A:a_j560485          B:b_y240674           Δtime=88s  Δamt=0.0100
📊 Matched CSV  → matched_pairs.csv
📊 Unmatched    → unmatched_a.csv
📊 Unmatched    → unmatched_b.csv

✅ Done! Files written:
   • reconciliation_report.json
   • reconciliation_summary.txt
   • matched_pairs.csv
   • unmatched_a.csv
   • unmatched_b.csv

# Pandas Solution

In [ ]:
import pandas as pd
import json
import re

# ── Load ──────────────────────────────────────────────────────────────────────
a_data = pd.read_json("./data/input_a.json")
b_data = pd.read_json("./data/input_b.json")

with open('./data/merchant_map.json') as f:
    matching_rules = json.load(f)

# ── Step 1: Clean & normalise merchant names ──────────────────────────────────
def clean_merchant(series):
    return series.str.replace(r'[,\-. ]', '', regex=True).str.lower()

# Clean the map keys too (same rules)
clean_map = {re.sub(r'[,\-. ]', '', k).lower(): v.lower()
             for k, v in matching_rules.items()}

a_data['merchant'] = clean_merchant(a_data['merchant']).map(clean_map).fillna(clean_merchant(a_data['merchant']))
b_data['merchant'] = clean_merchant(b_data['merchant']).map(clean_map).fillna(clean_merchant(b_data['merchant']))

# ── Step 2: Parse timestamps ───────────────────────────────────────────────────
a_data['ts'] = pd.to_datetime(a_data['ts'], utc=True)
b_data['ts'] = pd.to_datetime(b_data['ts'], utc=True)

# ── Step 3: Cross-join within same merchant ────────────────────────────────────
# merge on merchant → every A row paired with every B row of the same merchant
merged = a_data.merge(b_data, on='merchant', suffixes=('_a', '_b'))

# ── Step 4: Apply matching rules ───────────────────────────────────────────────
merged['time_diff_sec'] = (merged['ts_a'] - merged['ts_b']).abs().dt.total_seconds()
merged['amount_diff']   = (merged['amount_a'] - merged['amount_b']).abs()

time_ok   = merged['time_diff_sec'] <= 120
amount_ok = (merged['amount_diff'] <= 0.50) | \
            (merged['amount_diff'] / merged[['amount_a','amount_b']].max(axis=1) <= 0.001)

candidates = merged[time_ok & amount_ok].copy()

# ── Step 5: Greedy 1-to-1 matching (best time diff first) ─────────────────────
candidates = candidates.sort_values(['time_diff_sec', 'amount_diff'])

matched_a, matched_b = set(), set()
matched_rows = []

for _, row in candidates.iterrows():
    if row['id_a'] in matched_a or row['id_b'] in matched_b:
        continue
    matched_a.add(row['id_a'])
    matched_b.add(row['id_b'])
    matched_rows.append(row)

matched = pd.DataFrame(matched_rows) if matched_rows else pd.DataFrame()

# ── Step 6: Find unmatched ────────────────────────────────────────────────────
unmatched_a = a_data[~a_data['id'].isin(matched_a)]
unmatched_b = b_data[~b_data['id'].isin(matched_b)]

# ── Step 7: Summary ───────────────────────────────────────────────────────────
print("=" * 45)
print(f"  Total A          : {len(a_data)}")
print(f"  Total B          : {len(b_data)}")
print(f"  Matched pairs    : {len(matched)}")
print(f"  Unmatched A      : {len(unmatched_a)}")
print(f"  Unmatched B      : {len(unmatched_b)}")
print("=" * 45)

# ── Step 8: Save outputs ──────────────────────────────────────────────────────
if not matched.empty:
    matched[['id_a','merchant','amount_a','ts_a',
             'id_b','amount_b','ts_b',
             'time_diff_sec','amount_diff']].to_csv("matched_pairs.csv", index=False)

unmatched_a.to_csv("unmatched_a.csv", index=False)
unmatched_b.to_csv("unmatched_b.csv", index=False)

=============================================
  Total A          : 510
  Total B          : 500
  Matched pairs    : 440
  Unmatched A      : 70
  Unmatched B      : 60
=============================================